git:
  quiet: true
  sparse_checkout: .git/info/sparse-checkout
branches:
  only:
    - master
language: php
php:
  - 7.3
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.travis .env
  - sudo mysql -e 'create database opesDB;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
