git:
  quiet: true
  sparse_checkout: .github/sparse-checkout
branches:
  only:
    - testing
language: php
php:
  - 7.3
services:
  - mysql
cache:
  directories:
    - vendor
before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE wpesDB;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
#before_install:
script:
  - vendor/bin/phpunit -c phpunit.xml --verbose
#after_script:
#  - kill %1
#  - unset AID
