git:
  quiet: true
  sparse_checkout: .github/sparse-checkout
branches:
  only:
    - test
language: php
php:
  - 7.3
services:
  - mysql
cache:
  directories:
    - vendor
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan serve &
  - php artisan migrate
  - php artisan db:seed
  - cat .env
before_install:
  - sudo mysql -e 'CREATE DATABASE testing;'
script:
  - vendor/bin/phpunit -c phpunit.xml --verbose
after_script:
  - kill %1
  - unset AID
